pipeline:
    agent:
        any
    stages:
        - stage: Clone repository
          steps:
              - git: 'https://github.com/YakuppDemirr/InsiderTestCaseUI'
        - stage: Build and test
          steps:
              - sh: 'mvn clean test'