pipeline:
  agent:
    docker:
      image: maven:latest

  environment:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

  stages:
    - stage: Clone_Repository
      steps:
        - checkout scm

    - stage: Build
      steps:
        - sh 'mvn clean install'

    - stage: Test
      steps:
        - sh 'mvn test'
