name: Selenium Test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Install Maven
        run: |
          curl -fsSL -o apache-maven-3.8.4-bin.zip https://downloads.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip
          mkdir maven
          tar -xzf apache-maven-3.8.4-bin.zip -C maven --strip-components=1
          export PATH=$PWD/maven/bin:$PATH

      - name: Install Chrome
        run: |
          choco install googlechrome

      - name: Install ChromeDriver
        run: |
          choco install chromedriver

      - name: Run Selenium Tests
        run: |
          mvn clean test