name: Selenium Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Setup Maven
        uses: actions/setup-java@v1
        with:
          java-version: '14'
          maven-version: '3.8.4'

      - name: Install Chrome
        run: |
          choco install googlechrome

      - name: Install ChromeDriver
        run: |
          choco install chromedriver

      - name: Run Selenium Tests
        run: |
          mvn clean test
