name: Selenium Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Install Maven
        run: |
          curl -fsSL -o apache-maven-3.8.4-bin.zip https://downloads.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip
          mkdir maven
          Expand-Archive -Path "apache-maven-3.8.4-bin.zip" -DestinationPath "C:\extract\destination\folder"
          $myVariable | Export-Clixml -Path "C:\path\to\output.xml"

      - name: Install Chrome
        run: |
          choco install googlechrome

      - name: Install ChromeDriver
        run: |
          choco install chromedriver

      - name: Run Selenium Tests
        run: |
          mvn clean test
